# Generated by Django 5.2.6 on 2025-09-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='watched',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watching',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
